# Generated by Django 4.1.1 on 2022-10-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_documento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('paciente_tipodocumento', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('RC', 'RC')], max_length=2)),
                ('paciente_primernombre', models.CharField(max_length=60)),
                ('paciente_segundonombre', models.CharField(blank=True, max_length=60, null=True)),
                ('paciente_primerapellido', models.CharField(max_length=60)),
                ('paciente_segundoapellido', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientepatologias',
            fields=[
                ('pacpat_codigo', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pacientepatologias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('patologia_codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('patologia_nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
